export type Pattern = {
  slug: string;
  title: string;
  description: string;
  tags: string[];
  category: string;
  updatedAt: string;
  html: string;
  thumb: string;
};

export const patterns: Pattern[] = [
  {
    slug: "toast-undo",
    title: "Toast with undo",
    description: "Ephemeral confirmation with a short window to reverse the action.",
    tags: ["feedback", "toast"],
    category: "Feedback",
    updatedAt: "2026-09-08",
    html: "/patterns/toast-undo/index.html",
    thumb: "/patterns/toast-undo/thumb.svg",
  },
  {
    slug: "command-palette",
    title: "Command palette",
    description: "Keyboard-first search that jumps to actions without leaving the page.",
    tags: ["navigation", "keyboard"],
    category: "Navigation",
    updatedAt: "2026-09-07",
    html: "/patterns/command-palette/index.html",
    thumb: "/patterns/command-palette/thumb.svg",
  },
  {
    slug: "inline-validation",
    title: "Inline form validation",
    description: "Field-level errors as the user types, with a clear path to fix.",
    tags: ["forms", "errors"],
    category: "Forms",
    updatedAt: "2026-09-06",
    html: "/patterns/inline-validation/index.html",
    thumb: "/patterns/inline-validation/thumb.svg",
  },
  {
    slug: "empty-state",
    title: "Empty state",
    description: "A first-run view that explains why the space is empty and what to do next.",
    tags: ["onboarding", "content"],
    category: "Content",
    updatedAt: "2026-09-05",
    html: "/patterns/empty-state/index.html",
    thumb: "/patterns/empty-state/thumb.svg",
  },
  {
    slug: "skeleton-loading",
    title: "Skeleton loading",
    description: "Placeholder shapes that match the final layout while data loads.",
    tags: ["loading", "feedback"],
    category: "Feedback",
    updatedAt: "2026-09-04",
    html: "/patterns/skeleton-loading/index.html",
    thumb: "/patterns/skeleton-loading/thumb.svg",
  },
  {
    slug: "confirm-dialog",
    title: "Confirm dialog",
    description: "A pause before a destructive action, with cancel as the safe default.",
    tags: ["dialogs", "destructive"],
    category: "Dialogs",
    updatedAt: "2026-09-03",
    html: "/patterns/confirm-dialog/index.html",
    thumb: "/patterns/confirm-dialog/thumb.svg",
  },
  {
    slug: "visibility-system-status",
    title: "Visibility of system status",
    description: "Nielsen #1 — upload progress that keeps the user informed in real time.",
    tags: ["nielsen", "feedback", "status"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/visibility-system-status/index.html",
    thumb: "/patterns/visibility-system-status/thumb.svg",
  },
  {
    slug: "match-real-world",
    title: "Match the real world",
    description: "Nielsen #2 — plain language versus jargon on the same booking form.",
    tags: ["nielsen", "language", "forms"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/match-real-world/index.html",
    thumb: "/patterns/match-real-world/thumb.svg",
  },
  {
    slug: "user-control-freedom",
    title: "User control and freedom",
    description: "Nielsen #3 — cancel and back as emergency exits from a checkout wizard.",
    tags: ["nielsen", "navigation", "control"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/user-control-freedom/index.html",
    thumb: "/patterns/user-control-freedom/thumb.svg",
  },
  {
    slug: "consistency-standards",
    title: "Consistency and standards",
    description: "Nielsen #4 — same Save/Cancel treatment across panels, versus a confusing mismatch.",
    tags: ["nielsen", "consistency"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/consistency-standards/index.html",
    thumb: "/patterns/consistency-standards/thumb.svg",
  },
  {
    slug: "error-prevention",
    title: "Error prevention",
    description: "Nielsen #5 — date constraints that block an impossible range before submit.",
    tags: ["nielsen", "forms", "errors"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/error-prevention/index.html",
    thumb: "/patterns/error-prevention/thumb.svg",
  },
  {
    slug: "recognition-not-recall",
    title: "Recognition rather than recall",
    description: "Nielsen #6 — recent searches as chips so users recognize instead of remembering.",
    tags: ["nielsen", "search", "memory"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/recognition-not-recall/index.html",
    thumb: "/patterns/recognition-not-recall/thumb.svg",
  },
  {
    slug: "flexibility-efficiency",
    title: "Flexibility and efficiency",
    description: "Nielsen #7 — the same actions via buttons for novices and shortcuts for experts.",
    tags: ["nielsen", "keyboard", "efficiency"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/flexibility-efficiency/index.html",
    thumb: "/patterns/flexibility-efficiency/thumb.svg",
  },
  {
    slug: "aesthetic-minimalist",
    title: "Aesthetic and minimalist",
    description: "Nielsen #8 — strip promo clutter so the pay task stays visible.",
    tags: ["nielsen", "content", "focus"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/aesthetic-minimalist/index.html",
    thumb: "/patterns/aesthetic-minimalist/thumb.svg",
  },
  {
    slug: "error-recovery",
    title: "Error recovery",
    description: "Nielsen #9 — a declined payment explained in plain language with clear next steps.",
    tags: ["nielsen", "errors", "recovery"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/error-recovery/index.html",
    thumb: "/patterns/error-recovery/thumb.svg",
  },
  {
    slug: "help-documentation",
    title: "Help and documentation",
    description: "Nielsen #10 — searchable, in-context help with concrete steps beside a field.",
    tags: ["nielsen", "help", "docs"],
    category: "Heuristics",
    updatedAt: "2026-09-08",
    html: "/patterns/help-documentation/index.html",
    thumb: "/patterns/help-documentation/thumb.svg",
  },
];
